name: Run Checks

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - name: Shell script static analysis
        run: shellcheck bin/fetch-configlet bin/verify-unity-version bin/check-unitybegin format.sh

      - name: Check concept exercises formatting
        run: |
          find exercises/concept/ -path '*/test-framework' -prune -o \
            \( -iname '*.h' -o -iname '*.c' \) -print0 |\
            xargs --null clang-format --dry-run --Werror

      - name: Check practice exercises formatting
        run: |
          find exercises/practice/ -path '*/test-framework' -prune -o \
            \( -iname '*.h' -o -iname '*.c' \) -print0 |\
            xargs --null clang-format --dry-run --Werror

      - name: Check Unity version
        run: ./bin/verify-unity-version ./exercises/concept ./exercises/practice

      - name: Check unitybegin()
        run: ./bin/check-unitybegin ./exercises/concept ./exercises/practice

      - name: Check include guards
        run: ./bin/check-include-guards ./exercises/concept ./exercises/practice
