name: Test Exercises

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-24.04, macos-15]
        compiler: [gcc, clang]
        exclude:
          - os: macos-15
            compiler: gcc

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
    - name: Determine number of available hardware threads
      run: echo "NUM_THREADS=$(nproc || sysctl -n hw.ncpu)" >> $GITHUB_ENV
    - name: Test Exercises
      env:
        CC: ${{ matrix.compiler }}
      run: make -j ${{ env.NUM_THREADS }}
